title: Personal Portfolio # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: Jorge Aguirregomezcorta Aina # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer
  <br>
  <br>
  Videogame Designer and Developer
  <br>
  <br>
  <a href="https://www.linkedin.com/in/jorge-aguirregomezcorta-aina-811527197/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
